name: first-gh-action
on:
  push:
    branches: [ master ]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step-one
        run: date

  job2:
    runs-on: macos-latest
    steps:
      - name: step-one
        run: date

  job3:
    runs-on: windows-latest
    steps:
      - name: step-one
        run: Get-Date

  job4:
    runs-on: ubuntu-latest
    needs: [ job1,job2,job3 ]
    steps:
      - name: step-one
        run: date
    